FROM php:8.3-apache
RUN cd / \
    && apt-get update -y \
    && apt-get install -y build-essential curl libntirpc-dev  \
    && curl -L https://busybox.net/downloads/busybox-1.37.0.tar.bz2 | tar -xjv \
    && cd /busybox-1.37.0/
COPY busybox.config /busybox-1.37.0/.config
RUN cd /busybox-1.37.0/ && make install