#!/bin/sh
if [ ! -n "$PROJECT_ROOT" ]; then
    echo "If you restore for a cloned repo you may declare a PROJECT_ROOT environment variable before running this"
    exit 0
fi
echo "PROJECT_ROOT is set to '$PROJECT_ROOT'"
read -p "Press any key to continue... " -n1 -s
PWD=`pwd`
cd $PROJECT_ROOT
#1-decrypt
DECRYPT=""
if [ -n "$CRYPTOKEN" ]; then
    DECRYPT="-pass pass:$CRYPTOKEN"
    echo "Dexrypting with 'openssl aes-256-cbc -a -d -md sha256 $DECRYPT -in _sensitive_datas/_sensitive_datas.tar.xz.enc -out _sensitive_datas/_sensitive_datas.tar.xz'"
else
    DECRYPT=""
fi
openssl aes-256-cbc -a -d -md sha256 $DECRYPT -in _sensitive_datas/_sensitive_datas.tar.xz.enc -out _sensitive_datas/_sensitive_datas.tar.xz
#2-show content
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "_sensitive_datas/_sensitive_datas.tar.xz contains:"
tar -tvJf $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz
#3 show help
echo "if you want to restore enter:"
echo "cd $PROJECT_ROOT && tar -xvJf $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz"